apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-root
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-root
    app.kubernetes.io/part-of: purple-mermaid-app
  name: python-root
  namespace: jakumar
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: python-root
status:
  loadBalancer: {}
